### ISSUE TITLE
启用主题报错

### ISSUE THREAD

**Issue by jimicat** [ShawnZeng1996/reborn#1]
```bash
array_key_exists(): Argument #2 ($array) must be of type array, null given 
```
Typecho 版本：1.2.1

**Comment by ShawnZeng1996** [comment]
好的，我尝试复现一下，PHP版本是多少？

**Comment by jimicat** [comment]
> 好的，我尝试复现一下，PHP版本是多少？

php8.0 mysql8.4.2

**Comment by ShawnZeng1996** [comment]
我用PHP8.0试了下，也没有报错，你报错是在哪个页面，有用啥其他插件吗，另外可以加我QQ928200848详细描述下情况

**Comment by ShawnZeng1996** [comment]
https://github.com/typecho/typecho/pull/1591/files/98e2011927f0c7253412abce0248c9ea2f9a7db0

**Comment by ShawnZeng1996** [comment]
参考这篇文章改一下，貌似是 typecho 的 bug
